# Generated by Django 2.2.14 on 2020-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMPASJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField()),
                ('public', models.BooleanField(default=False)),
                ('download_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
