# Generated by Django 2.2.14 on 2020-08-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='COMPASJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('journal', models.CharField(max_length=255, null=True)),
                ('journal_DOI', models.CharField(max_length=255, null=True)),
                ('dataset_DOI', models.CharField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('download_link', models.TextField(blank=True, null=True)),
                ('arxiv_id', models.CharField(max_length=255)),
                ('keywords', models.ManyToManyField(to='compasweb.Keyword')),
            ],
        ),
    ]
