# Generated by Django 2.2.14 on 2020-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compasjob',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='datasets/'),
        ),
    ]
