# Generated by Django 2.2.14 on 2020-09-09 11:47

import compasweb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compasweb', '0002_compasjob_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compasjob',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=compasweb.models.job_directory_path),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=compasweb.models.job_directory_path)),
                ('compasjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compasweb.COMPASJob')),
            ],
        ),
    ]
