# Generated by Django 2.2.14 on 2020-10-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasweb', '0004_auto_20200921_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compasmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
