# Generated by Django 2.2.14 on 2021-01-11 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasweb', '0005_auto_20201028_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMPASModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass1', models.FloatField(default=0.0, help_text='Mass of the initially more massive star', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)])),
                ('mass2', models.FloatField(default=0.0, help_text='Mass of the initially less massive star', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)])),
                ('metallicity', models.FloatField(default=0.0142, help_text='Metallicity of stars', validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(0.03)])),
                ('eccentricity', models.FloatField(default=0.0, help_text='Orbital eccentricity of the binary', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)])),
                ('seperation', models.FloatField(default=0.0, help_text='Orbital separation of the binary', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('orbital_period', models.FloatField(default=0.0, help_text='Orbital period of the binary', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_time', models.FloatField(default=0, help_text='Maximum time to evolve binary for', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1400)])),
                ('velocity_random_number', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('velocity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('theta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)])),
                ('phi', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)])),
                ('mean_anomaly', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)])),
                ('common_envelope_alpha', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('common_envelope_lambda_prescription', models.CharField(choices=[('LAMBDA_FIXED', 'LAMBDA_FIXED'), ('LAMBDA_KRUCKOW', 'LAMBDA_KRUCKOW'), ('LAMBDA_LOVERIDGE', 'LAMBDA_LOVERIDGE'), ('LAMBDA_NANJING', 'LAMBDA_NANJING'), ('LAMBDA_DEWI', 'LAMBDA_DEWI')], default='LAMBDA_NANJING', max_length=55)),
                ('common_envelope_lambda', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remnant_mass_prescription', models.CharField(choices=[('HURLEY2000', 'HURLEY2000'), ('BELCZYNSKI2002', 'BELCZYNSKI2002'), ('FRYER2012', 'FRYER2012'), ('MULLER2016', 'MULLER2016'), ('MULLERMANDEL', 'MULLERMANDEL')], default='FRYER2012', max_length=55)),
                ('fryer_supernova_engine', models.CharField(choices=[('DELAYED', 'DELAYED'), ('RAPID', 'RAPID')], default='DELAYED', max_length=55)),
                ('black_hole_kicks', models.CharField(choices=[('FALLBACK', 'FALLBACK'), ('FULL', 'FULL'), ('REDUCED', 'REDUCED'), ('ZERO', 'ZERO')], default='FALLBACK', max_length=55)),
                ('Kick_velocity_distribution', models.CharField(choices=[('ZERO', 'ZERO'), ('FIXED', 'FIXED'), ('FLAT', 'FLAT'), ('MAXWELLIAN', 'MAXWELLIAN'), ('BRAYELDRIDGE', 'BRAYELDRIDGE'), ('MULLER2016', 'MULLER2016'), ('MULLER2016MAXWELLIAN', 'MULLER2016MAXWELLIAN'), ('MULLERMANDEL', 'MULLERMANDEL')], default='MAXWELLIAN', max_length=55)),
                ('kick_velocity_sigma_CCSN_NS', models.FloatField(default=256.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('kick_velocity_sigma_CCSN_BH', models.FloatField(default=256.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('kick_velocity_sigma_ECSN', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('kick_velocity_sigma_USSN', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pair_instability_supernovae', models.BooleanField(default=True)),
                ('pisn_lower_limit', models.FloatField(default=60.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pisn_upper_limit', models.FloatField(default=135.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pulsational_pair_instability_supernovae', models.BooleanField(default=True)),
                ('ppi_lower_limit', models.FloatField(default=35.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ppi_upper_limit', models.FloatField(default=60.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pulsational_pair_instability_prescription', models.CharField(choices=[('COMPAS', 'COMPAS'), ('STARTRACK', 'STARTRACK'), ('MARCHANT', 'MARCHANT')], default='MARCHANT', max_length=55)),
                ('maximum_neutron_star_mass', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mass_transfer_angular_momentum_loss_prescription', models.CharField(choices=[('ARBITRARY', 'ARBITRARY'), ('ISOTROPIC', 'ISOTROPIC'), ('JEANS', 'JEANS'), ('CIRCUMBINARY', 'CIRCUMBINARY')], default='ISOTROPIC', max_length=55)),
                ('mass_transfer_accertion_efficiency_prescription', models.CharField(choices=[('THERMAL', 'THERMAL'), ('FIXED', 'FIXED')], default='THERMAL', max_length=55)),
                ('mass_transfer_fa', models.FloatField(default=0.5, help_text='Mass Transfer fraction accreted in FIXED prescription', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mass_transfer_jloss', models.FloatField(default=1.0, help_text='Specific angular momentum with which the non-accreted system leaves the system', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
