# Generated by Django 2.2.14 on 2021-04-14 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasweb', '0010_auto_20210413_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compasmodelrun',
            name='common_envelope_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='kick_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='kick_velocity_sigma_USSN',
            field=models.FloatField(blank=True, default=30.0, help_text='--kick-magnitude-sigma-USSN: Sigma for chosen kick magnitude distribution for USSN (km s − 1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='mass_transfer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='supernova_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
