# Generated by Django 2.2.14 on 2021-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasweb', '0011_auto_20210415_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compasmodelrun',
            name='common_envelope_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='kick_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='mass_transfer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compasmodelrun',
            name='supernova_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
