[tool.poetry]
name = "ss20b-sstevenson"
version = "0.1.0"
description = ""
authors = ["GWDC"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "<3"
numpy = "^1.19.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
